### PR TITLE
Paste motif name to left of sequence logo and increase width of graph

### PR DESCRIPTION
**Pull request by krish8484**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Addresses #34 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not reduced the existing code coverage

### CODE REVIEW

**Comment by krish8484** [comment]
Even after this PR, there is a limit of how much information one can show in a single PDF. The graph may still not look very pretty if the input sequence length increases to 200.

**Comment by AngryMaciek** [comment]
Why is that? what parts "will not be pretty?". For long sequences you can turn off the letter annotation of columns, as I mentioned in the issue, right?
It is highly possible that in real life we will work with sequences of hundreds of letters.

**Comment by krish8484** [comment]
Actually, its not bad, I ran the pipeline for an input sequence length of 300. This is the graph I got. One may have to use a good PDF viewer, so they can zoom in to view the graph clearly. For instance, opening it in Google Chrome will be good.
[ProbabilityVsSequence.pdf](https://github.com/zavolanlab/binding-scanner/files/5049540/ProbabilityVsSequence.pdf)

**Comment by AngryMaciek** [comment]
Ok, this one is not bad,
Let's make a test at maximum capacity - could you please run with a seq.len=1000 and full ATtRACT db and post the picture here as well?

**Comment by AngryMaciek** [comment]
The plot might look good but it is too heavy to parse by PDF viewers. As my system says - the image resolution is `18792 × 85248`... You need to reduce the size of the file - currently me, a potential user, cannot even open it neither on mac nor Ubuntu.
PTry to look into distinct formats, encoding etc.

**Comment by krish8484** [comment]
I tried plotting the graph in `png`, `jpeg`, `tiff` and `svg`
`png`, `jpeg` and `tiff` returned an error due to image size (after googling about the error)
`Error in grDevices::png(..., res = dpi, units = "in") :    unable to start device 'png'`.
Even after the scaling it down, using `scale` parameter, the `jpeg` image is not even close to good.
`svg` file is too large, around 280 Mb

**Comment by AngryMaciek** [comment]
OK, let's leave it the way it is for now. It is OK for regular use-case.
For a proper presentation of **FULL ATtRACT** database and **very long** sequences we will have to come up with another approach...

**Pull request merged**
